## BASIC PROGRAMS (NUMPY)

#### 1) Broadcasting in NumPy

In [1]:
import numpy as np

A = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
B = np.array([1, 2, 3])

print("Multiplication with broadcasting: ")
print(A * B)

print("... and now addition with broadcasting: ")
print(A + B)

Multiplication with broadcasting: 
[[11 24 39]
 [21 44 69]
 [31 64 99]]
... and now addition with broadcasting: 
[[12 14 16]
 [22 24 26]
 [32 34 36]]


#### 2) Arithmetic & matrices operations:


In [2]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

add_ans = np.add(a, b)
print(add_ans)

sum = np.sum(add_ans)
print(sum)

sub_ans = np.subtract(a, b)
print(sub_ans)

mul_ans = np.multiply(a, b)
print(mul_ans)

div_ans = np.divide(a, b)
print(div_ans)

[  7  77  23 130]
237
[ 3 67  3 70]
[  10  360  130 3000]
[ 2.5        14.4         1.3         3.33333333]


In [3]:
# Matrices operations:
import numpy as np

matrix1 = np.array([[1, 3], [5, 7]])
matrix2 = np.array([[2, 6], [4, 8]])

mod_ans = np.mod(matrix1, matrix2)
print("mod_ans : \n", mod_ans)

rem_ans = np.remainder(matrix1, matrix2)
print("rem_ans : \n", rem_ans)

pow_ans = np.power(matrix1, matrix2)
print("pow_ans : \n", pow_ans)

result = np.dot(matrix1, matrix2)
print("result : \n", result)

result = np.transpose(matrix1)
print("result : \n", result)

mod_ans : 
 [[1 3]
 [1 7]]
rem_ans : 
 [[1 3]
 [1 7]]
pow_ans : 
 [[      1     729]
 [    625 5764801]]
result : 
 [[14 30]
 [38 86]]
result : 
 [[1 5]
 [3 7]]


#### 3) NumPy program to create a structured array from given student name, height, class, and their data types, and then sort the array by height:


In [4]:
import numpy as np

data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.10), ('Pit', 5, 40.11)]
students = np.array(students_details, dtype=data_type)

print("Original array:")
print(students)

print("Sort by height:")
print(np.sort(students, order='height'))

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height:
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


#### 4) Write a NumPy program to compute the determinant of a square array:


In [5]:
import numpy as np

data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.10), ('Pit', 5, 40.11)]
students = np.array(students_details, dtype=data_type)

print("Original array:")
print(students)

print("Sort by height:")
print(np.sort(students, order='height'))

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height:
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


#### 4) Write a NumPy program to compute the determinant of a square array:


In [7]:
import numpy as np

n_array = np.array([[50, 29], [30, 44]])
det = np.linalg.det(n_array)

print("\nDeterminant of given 2x2 matrix:")
print(int(det))


Determinant of given 2x2 matrix:
1330


### 5) Demonstrate NumPy indexing and slicing with an example:


In [8]:
import numpy as np

arr = np.arange(16)
print("arr : ", arr)

print("Element at index 10 : ", arr[10])
print(arr[1:7])

import numpy as np

a = np.arange(10)
b = a[2:7:2]
print(b)

a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print(a)
print(a[1:])
print(a[1][2])
print(a[2])

arr :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Element at index 10 :  10
[1 2 3 4 5 6]
[2 4 6]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]
5
[4 5 6]
